# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hologram_pb2 as hologram__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hologram_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HologramGeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateHologram = channel.unary_unary(
                '/hologram.HologramGeneratorService/GenerateHologram',
                request_serializer=hologram__pb2.HologramRequest.SerializeToString,
                response_deserializer=hologram__pb2.HologramResponse.FromString,
                _registered_method=True)


class HologramGeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateHologram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HologramGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateHologram': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHologram,
                    request_deserializer=hologram__pb2.HologramRequest.FromString,
                    response_serializer=hologram__pb2.HologramResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hologram.HologramGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hologram.HologramGeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HologramGeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateHologram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hologram.HologramGeneratorService/GenerateHologram',
            hologram__pb2.HologramRequest.SerializeToString,
            hologram__pb2.HologramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
