# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hologram.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'hologram.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehologram.proto\x12\x08hologram\"\x94\x03\n\x0fHologramRequest\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\x12\x12\n\niterations\x18\x04 \x01(\x05\x12\x0e\n\x06is_rgb\x18\x05 \x01(\x08\x12\x17\n\x0fis_apply_affine\x18\x06 \x01(\x08\x12\x0f\n\x07x_array\x18\x07 \x01(\x0c\x12\x0f\n\x07y_array\x18\x08 \x01(\x0c\x12\x0f\n\x07z_array\x18\t \x01(\x0c\x12\x17\n\x0fintensity_array\x18\n \x01(\x0c\x12\x0f\n\x07SLM_X_0\x18\x0b \x01(\x02\x12\x0f\n\x07SLM_Y_0\x18\x0c \x01(\x02\x12\x0f\n\x07\x43\x41M_X_0\x18\r \x01(\x02\x12\x0f\n\x07\x43\x41M_Y_0\x18\x0e \x01(\x02\x12\x0f\n\x07SLM_X_1\x18\x0f \x01(\x02\x12\x0f\n\x07SLM_Y_1\x18\x10 \x01(\x02\x12\x0f\n\x07\x43\x41M_X_1\x18\x11 \x01(\x02\x12\x0f\n\x07\x43\x41M_Y_1\x18\x12 \x01(\x02\x12\x0f\n\x07SLM_X_2\x18\x13 \x01(\x02\x12\x0f\n\x07SLM_Y_2\x18\x14 \x01(\x02\x12\x0f\n\x07\x43\x41M_X_2\x18\x15 \x01(\x02\x12\x0f\n\x07\x43\x41M_Y_2\x18\x16 \x01(\x02\"I\n\x10HologramResponse\x12\x16\n\x0ehologram_image\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x32\x65\n\x18HologramGeneratorService\x12I\n\x10GenerateHologram\x12\x19.hologram.HologramRequest\x1a\x1a.hologram.HologramResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hologram_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLOGRAMREQUEST']._serialized_start=29
  _globals['_HOLOGRAMREQUEST']._serialized_end=433
  _globals['_HOLOGRAMRESPONSE']._serialized_start=435
  _globals['_HOLOGRAMRESPONSE']._serialized_end=508
  _globals['_HOLOGRAMGENERATORSERVICE']._serialized_start=510
  _globals['_HOLOGRAMGENERATORSERVICE']._serialized_end=611
# @@protoc_insertion_point(module_scope)
