# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\x0cimageservice\"<\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\" \n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x05\x32U\n\x0cImageService\x12\x45\n\nLocateTask\x12\x1a.imageservice.ImageRequest\x1a\x1b.imageservice.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=37
  _globals['_IMAGEREQUEST']._serialized_end=97
  _globals['_IMAGERESPONSE']._serialized_start=99
  _globals['_IMAGERESPONSE']._serialized_end=131
  _globals['_IMAGESERVICE']._serialized_start=133
  _globals['_IMAGESERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
